project:
  type: website

website:
  title: "ClimED"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: datasum.qmd
        text: Data summary
      - href: members.qmd
        text: Members
      - href: pubs.qmd
        text: Publications

format:
  html:
    theme: simplex
    css: styles.css
    toc: true